/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ktmeta;

import javax.swing.ImageIcon;
import java.awt.image.BufferedImage;

/**
 * @author ckhoi
 */
public class KtmetaJFrame extends javax.swing.JFrame {

    /**
     * Creates new form KtmetaJFrame
     */
    public KtmetaJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainToolBar = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton3 = new javax.swing.JButton();
        MainSplitPane = new javax.swing.JSplitPane();
        SubRightSplitPane = new javax.swing.JSplitPane();
        CentreSplit = new javax.swing.JPanel();
        GeneralTabbedPaneTemplate = new javax.swing.JTabbedPane();
        GeneralSplitPaneTemplate = new javax.swing.JSplitPane();
        GeneralUpperPaneTemplate = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        GeneralDownTabbedPaneTemplate = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        RightSplit = new javax.swing.JPanel();
        SubLeftTabbedPane = new javax.swing.JTabbedPane();
        LTScrollPane = new javax.swing.JScrollPane();
        LibraryTree = new javax.swing.JTree();
        MainMenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        EditMenu = new javax.swing.JMenu();
        ToolsMenu = new javax.swing.JMenu();
        ToolsPrefItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenu();
        HelpAboutItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(1440, 900));
        setName("MainFrame"); // NOI18N
        setSize(new java.awt.Dimension(1440, 900));

        MainToolBar.setRollover(true);

        jButton2.setText("jButton2");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MainToolBar.add(jButton2);
        MainToolBar.add(jSeparator1);

        jButton3.setText("jButton3");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        MainToolBar.add(jButton3);

        MainSplitPane.setOneTouchExpandable(true);

        SubRightSplitPane.setOneTouchExpandable(true);

        CentreSplit.setMinimumSize(new java.awt.Dimension(900, 100));
        CentreSplit.setPreferredSize(new java.awt.Dimension(900, 803));

        GeneralSplitPaneTemplate.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        GeneralUpperPaneTemplate.setPreferredSize(new java.awt.Dimension(900, 600));

        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout GeneralUpperPaneTemplateLayout = new javax.swing.GroupLayout(GeneralUpperPaneTemplate);
        GeneralUpperPaneTemplate.setLayout(GeneralUpperPaneTemplateLayout);
        GeneralUpperPaneTemplateLayout.setHorizontalGroup(
                GeneralUpperPaneTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        GeneralUpperPaneTemplateLayout.setVerticalGroup(
                GeneralUpperPaneTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        GeneralSplitPaneTemplate.setTopComponent(GeneralUpperPaneTemplate);

        GeneralDownTabbedPaneTemplate.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane1.setViewportView(jEditorPane1);

        GeneralDownTabbedPaneTemplate.addTab("tab1", jScrollPane1);
        GeneralDownTabbedPaneTemplate.addTab("tab2", jSplitPane2);

        GeneralSplitPaneTemplate.setRightComponent(GeneralDownTabbedPaneTemplate);

        GeneralTabbedPaneTemplate.addTab("tab1", GeneralSplitPaneTemplate);

        javax.swing.GroupLayout CentreSplitLayout = new javax.swing.GroupLayout(CentreSplit);
        CentreSplit.setLayout(CentreSplitLayout);
        CentreSplitLayout.setHorizontalGroup(
                CentreSplitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(GeneralTabbedPaneTemplate)
        );
        CentreSplitLayout.setVerticalGroup(
                CentreSplitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(GeneralTabbedPaneTemplate)
        );

        SubRightSplitPane.setLeftComponent(CentreSplit);

        javax.swing.GroupLayout RightSplitLayout = new javax.swing.GroupLayout(RightSplit);
        RightSplit.setLayout(RightSplitLayout);
        RightSplitLayout.setHorizontalGroup(
                RightSplitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 326, Short.MAX_VALUE)
        );
        RightSplitLayout.setVerticalGroup(
                RightSplitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 803, Short.MAX_VALUE)
        );

        SubRightSplitPane.setRightComponent(RightSplit);

        MainSplitPane.setRightComponent(SubRightSplitPane);

        SubLeftTabbedPane.setMinimumSize(new java.awt.Dimension(200, 100));
        SubLeftTabbedPane.setPreferredSize(new java.awt.Dimension(200, 100));

        LTScrollPane.setViewportView(LibraryTree);

        SubLeftTabbedPane.addTab("Libraries", LTScrollPane);

        MainSplitPane.setLeftComponent(SubLeftTabbedPane);

        FileMenu.setText("File");
        MainMenuBar.add(FileMenu);

        EditMenu.setText("Edit");
        MainMenuBar.add(EditMenu);

        ToolsMenu.setText("Tools");

        ToolsPrefItem.setIcon(new ImageIcon(new BufferedImage(20, 20, BufferedImage.TYPE_INT_ARGB)));
        ToolsPrefItem.setText("Preference");
        ToolsPrefItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToolsPrefItemActionPerformed(evt);
            }
        });
        ToolsMenu.add(ToolsPrefItem);
        ToolsMenu.add(jSeparator2);

        jMenuItem1.setIcon(new ImageIcon(new BufferedImage(20, 20, BufferedImage.TYPE_INT_ARGB)));
        jMenuItem1.setText("ElasticSearch");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        ToolsMenu.add(jMenuItem1);

        MainMenuBar.add(ToolsMenu);

        HelpMenu.setText("Help");

        HelpAboutItem.setIcon(new ImageIcon(new BufferedImage(20, 20, BufferedImage.TYPE_INT_ARGB)));
        HelpAboutItem.setText("About");
        HelpAboutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpAboutItemActionPerformed(evt);
            }
        });
        HelpMenu.add(HelpAboutItem);

        MainMenuBar.add(HelpMenu);

        setJMenuBar(MainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MainToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MainSplitPane)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(MainToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(MainSplitPane)
                                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HelpAboutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpAboutItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HelpAboutItemActionPerformed

    private void ToolsPrefItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToolsPrefItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToolsPrefItemActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
            javax.swing.UIManager.setLookAndFeel("MaterialOceanicTheme");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KtmetaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KtmetaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KtmetaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KtmetaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KtmetaJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JPanel CentreSplit;
    protected javax.swing.JMenu EditMenu;
    protected javax.swing.JMenu FileMenu;
    protected javax.swing.JTabbedPane GeneralDownTabbedPaneTemplate;
    protected javax.swing.JSplitPane GeneralSplitPaneTemplate;
    protected javax.swing.JTabbedPane GeneralTabbedPaneTemplate;
    protected javax.swing.JPanel GeneralUpperPaneTemplate;
    protected javax.swing.JMenuItem HelpAboutItem;
    protected javax.swing.JMenu HelpMenu;
    protected javax.swing.JScrollPane LTScrollPane;
    protected javax.swing.JTree LibraryTree;
    protected javax.swing.JMenuBar MainMenuBar;
    protected javax.swing.JSplitPane MainSplitPane;
    protected javax.swing.JToolBar MainToolBar;
    protected javax.swing.JPanel RightSplit;
    protected javax.swing.JTabbedPane SubLeftTabbedPane;
    private javax.swing.JSplitPane SubRightSplitPane;
    protected javax.swing.JMenu ToolsMenu;
    protected javax.swing.JMenuItem ToolsPrefItem;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
